version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: deadlinks check
          command: |
            sudo python3 -m pip install deadlinks==0.2.0
            deadlinks internal -R docs --fiff --no-progress --no-colors
