version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: requirements
          command: |
            sudo python3 -m pip install deadlinks
            sudo python3 -m pip install -r requirements-docs.txt

      - run:
          name: "deadlinks: checking external service"
          command: |
            mkdocs serve -q &
            deadlinks http://127.0.0.1:8000 -n10 --no-progress --no-colors

      # - run:
      #     name: "deadlinks: static files checks"
      #     command: |
      #       mkdocs build -d site
      #       deadlinks internal -R site --fiff --no-progress --no-colors
