defaults: &defaults
  docker:
    - image: circleci/python:3.8
  working_directory: ~/repo


version: 2
jobs:

  tests-n-builds: # Tests : Installing requirements and running initial test (against web server)
    docker:
    - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: "Python: install requirements"
        command: |
          sudo python3 -m pip install git+https://github.com/butuzov/deadlinks@develop
          sudo python3 -m pip install -r requirements-docs.txt

    - run:
        name: "Deadlinks: checking external (web) resource"
        command: |
          mkdocs serve -q &
          deadlinks http://127.0.0.1:8000 -n10 -r3 --fiff --no-progress --no-colors

    - run:
        name: "Building artifacts (Documentation)"
        command:  mkdocs build -d site

    - run:
        name: "Deadlinks: checking internal (files) resource"
        command: deadlinks internal -n10 -r3 --root=site --fiff --no-progress --no-colors

    - persist_to_workspace:
        root: site
        paths: .

  # Deploy to github pages.
  deploy:
    docker:
    - image: circleci/node:12.13
    working_directory: ~/repo

    steps:
    - checkout
    - run:
        name: Prepare branches locally
        command: |
          git checkout gh-pages
          git checkout master

    - run:
        name: Set up gh-pages in worktree for easy artifact copying
        command: |
          mkdir ../gh-pages
          git worktree add ../gh-pages gh-pages


    - attach_workspace:
        at: site

    - run:
        name: Disable jekyll builds
        command: touch site/.nojekyll

    - add_ssh_keys:
        fingerprints:
          - "cd:4e:8a:73:71:fe:86:64:cc:5d:0f:eb:dc:f5:db:88"

    - run:
        name: "GitHub Pages deployment"
        command: |
          rm -r ../gh-pages/*
          cp -r site/* ../gh-pages
          cd ../gh-pages
          ls -la
          git config --global user.email "miaugav@ukr.net"
          git config --global user.name   "CircleCI"
          git add .
          git commit --allow-empty -m "Build triggered by CircleCI"
          git push -u origin gh-pages


workflows:
  version: 2
  test-build-and-deploy:
    jobs:
    - tests-n-builds:
        filters:
          branches: { ignore: "gh-pages" }

    - deploy:
        requires:
        - tests-n-builds
        filters:
          branches: { only: "master" }
